import { customAlphabet } from "nanoid";
import { getDb } from "./client.js";
import { hashPassword, verifyPassword as verifyPasswordHash } from "../auth/password.js";

// Alphanumeric only — these ids end up in REST URLs, so avoid characters
// that are awkward there (e.g. a leading '-' from the default alphabet).
const nanoid = customAlphabet("0123456789abcdefghijklmnopqrstuvwxyz", 10);

export interface Repo {
  id: string;
  name: string;
  bare_path: string;
  default_branch: string;
  created_at: string;
}

export interface Participant {
  id: string;
  repo_id: string;
  display_name: string;
  email: string;
  role: string;
  password_hash: string | null;
  created_at: string;
}

export type PrStatus = "open" | "rejected" | "merged" | "closed";
export type PrEventType = "created" | "pushed" | "approved" | "rejected" | "merged" | "closed" | "comment";

export interface PullRequest {
  id: string;
  repo_id: string;
  branch: string;
  target_branch: string;
  status: PrStatus;
  title: string | null;
  base_branch: string | null;
  author_email: string | null;
  turn_email: string | null;
  head_sha: string;
  base_sha: string;
  created_at: string;
  updated_at: string;
}

export interface PrEvent {
  id: number;
  pr_id: string;
  type: PrEventType;
  actor_email: string | null;
  sha: string | null;
  comment: string | null;
  created_at: string;
}

export const reposRepo = {
  /** id is generated by the caller (repoService) since it's needed up front
   * to compute the bare repo's filesystem path before the row is inserted. */
  create(input: { id: string; name: string; barePath: string; defaultBranch?: string }): Repo {
    getDb()
      .prepare(
        `INSERT INTO repos (id, name, bare_path, default_branch) VALUES (?, ?, ?, ?)`
      )
      .run(input.id, input.name, input.barePath, input.defaultBranch ?? "main");
    return reposRepo.get(input.id)!;
  },
  get(id: string): Repo | undefined {
    return getDb().prepare(`SELECT * FROM repos WHERE id = ?`).get(id) as Repo | undefined;
  },
  findByName(name: string): Repo | undefined {
    return getDb().prepare(`SELECT * FROM repos WHERE name = ?`).get(name) as Repo | undefined;
  },
  list(): Repo[] {
    return getDb().prepare(`SELECT * FROM repos ORDER BY created_at DESC`).all() as Repo[];
  },
  /** Cascades to participants, pull_requests, and pr_events via their
   * ON DELETE CASCADE foreign keys — does not touch the bare repo on disk. */
  delete(id: string): void {
    getDb().prepare(`DELETE FROM repos WHERE id = ?`).run(id);
  },
};

export const participantsRepo = {
  /** `password`, when given, is hashed before storage — never persisted in
   * plaintext. Re-adding an existing (repoId, email) updates the display
   * name and, only if a new password was passed, replaces the password hash
   * (an omitted password leaves the existing credential untouched). */
  add(input: {
    repoId: string;
    displayName: string;
    email: string;
    role?: string;
    password?: string;
  }): Participant {
    const id = nanoid(10);
    const passwordHash = input.password ? hashPassword(input.password) : null;
    getDb()
      .prepare(
        `INSERT INTO participants (id, repo_id, display_name, email, role, password_hash)
         VALUES (?, ?, ?, ?, ?, ?)
         ON CONFLICT(repo_id, email) DO UPDATE SET
           display_name = excluded.display_name,
           password_hash = COALESCE(excluded.password_hash, participants.password_hash)`
      )
      .run(id, input.repoId, input.displayName, input.email, input.role ?? "party", passwordHash);
    return getDb()
      .prepare(`SELECT * FROM participants WHERE repo_id = ? AND email = ?`)
      .get(input.repoId, input.email) as Participant;
  },
  listForRepo(repoId: string): Participant[] {
    return getDb()
      .prepare(`SELECT * FROM participants WHERE repo_id = ? ORDER BY created_at ASC`)
      .all(repoId) as Participant[];
  },
  findByEmail(repoId: string, email: string): Participant | undefined {
    return getDb()
      .prepare(`SELECT * FROM participants WHERE repo_id = ? AND email = ?`)
      .get(repoId, email) as Participant | undefined;
  },
  /** Checks a plaintext password against the stored hash for this
   * participant. A participant with no password set (e.g. added before
   * credentials existed) never verifies — they need a password issued via
   * `gitlaw participant add` before they can authenticate. */
  verifyPassword(repoId: string, email: string, password: string): boolean {
    const participant = participantsRepo.findByEmail(repoId, email);
    if (!participant?.password_hash) return false;
    return verifyPasswordHash(password, participant.password_hash);
  },
  /** The "other" party relative to an actor, used only for the advisory turn badge. */
  otherParty(repoId: string, actorEmail: string | null): string | null {
    const participants = participantsRepo.listForRepo(repoId);
    const other = participants.find((p) => p.email !== actorEmail);
    return other?.email ?? null;
  },
};

export const prRepo = {
  findOpenByBranch(repoId: string, branch: string): PullRequest | undefined {
    return getDb()
      .prepare(`SELECT * FROM pull_requests WHERE repo_id = ? AND branch = ? AND status = 'open'`)
      .get(repoId, branch) as PullRequest | undefined;
  },
  findAnyByBranch(repoId: string, branch: string): PullRequest | undefined {
    return getDb()
      .prepare(
        `SELECT * FROM pull_requests WHERE repo_id = ? AND branch = ? ORDER BY created_at DESC LIMIT 1`
      )
      .get(repoId, branch) as PullRequest | undefined;
  },
  get(id: string): PullRequest | undefined {
    return getDb().prepare(`SELECT * FROM pull_requests WHERE id = ?`).get(id) as
      | PullRequest
      | undefined;
  },
  listForRepo(repoId: string, status?: PrStatus): PullRequest[] {
    if (status) {
      return getDb()
        .prepare(`SELECT * FROM pull_requests WHERE repo_id = ? AND status = ? ORDER BY created_at DESC`)
        .all(repoId, status) as PullRequest[];
    }
    return getDb()
      .prepare(`SELECT * FROM pull_requests WHERE repo_id = ? ORDER BY created_at DESC`)
      .all(repoId) as PullRequest[];
  },
  create(input: {
    repoId: string;
    branch: string;
    targetBranch: string;
    headSha: string;
    baseSha: string;
    baseBranch: string | null;
    authorEmail: string | null;
    turnEmail: string | null;
  }): PullRequest {
    const id = nanoid(10);
    getDb()
      .prepare(
        `INSERT INTO pull_requests
           (id, repo_id, branch, target_branch, status, author_email, turn_email, head_sha, base_sha, base_branch)
         VALUES (?, ?, ?, ?, 'open', ?, ?, ?, ?, ?)`
      )
      .run(
        id,
        input.repoId,
        input.branch,
        input.targetBranch,
        input.authorEmail,
        input.turnEmail,
        input.headSha,
        input.baseSha,
        input.baseBranch
      );
    return prRepo.get(id)!;
  },
  updateHeadSha(id: string, headSha: string): void {
    getDb()
      .prepare(`UPDATE pull_requests SET head_sha = ?, updated_at = datetime('now') WHERE id = ?`)
      .run(headSha, id);
  },
  setStatus(id: string, status: PrStatus): void {
    getDb()
      .prepare(`UPDATE pull_requests SET status = ?, updated_at = datetime('now') WHERE id = ?`)
      .run(status, id);
  },
  setTurn(id: string, turnEmail: string | null): void {
    getDb()
      .prepare(`UPDATE pull_requests SET turn_email = ?, updated_at = datetime('now') WHERE id = ?`)
      .run(turnEmail, id);
  },
  /** Cascades to pr_events via its ON DELETE CASCADE foreign key. Does not
   * touch the branch in the bare repo — a re-push recreates the PR row. */
  delete(id: string): void {
    getDb().prepare(`DELETE FROM pull_requests WHERE id = ?`).run(id);
  },
};

export const eventsRepo = {
  insert(input: {
    prId: string;
    type: PrEventType;
    actorEmail?: string | null;
    sha?: string | null;
    comment?: string | null;
  }): PrEvent {
    const result = getDb()
      .prepare(
        `INSERT INTO pr_events (pr_id, type, actor_email, sha, comment) VALUES (?, ?, ?, ?, ?)`
      )
      .run(input.prId, input.type, input.actorEmail ?? null, input.sha ?? null, input.comment ?? null);
    return getDb().prepare(`SELECT * FROM pr_events WHERE id = ?`).get(result.lastInsertRowid) as PrEvent;
  },
  listForPr(prId: string): PrEvent[] {
    return getDb()
      .prepare(`SELECT * FROM pr_events WHERE pr_id = ? ORDER BY created_at ASC, id ASC`)
      .all(prId) as PrEvent[];
  },
};
